set_property SRC_FILE_INFO {cfile:D:/Project/UDP_PRO/rgmii_ethernet/rgmii_ethernet.srcs/constrs_1/new/ethernet_test.xdc rfile:../rgmii_ethernet.srcs/constrs_1/new/ethernet_test.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {u1/u1/iprecieve_inst/rx_data_length[0]} {u1/u1/iprecieve_inst/rx_data_length[1]} {u1/u1/iprecieve_inst/rx_data_length[2]} {u1/u1/iprecieve_inst/rx_data_length[3]} {u1/u1/iprecieve_inst/rx_data_length[4]} {u1/u1/iprecieve_inst/rx_data_length[5]} {u1/u1/iprecieve_inst/rx_data_length[6]} {u1/u1/iprecieve_inst/rx_data_length[7]} {u1/u1/iprecieve_inst/rx_data_length[8]} {u1/u1/iprecieve_inst/rx_data_length[9]} {u1/u1/iprecieve_inst/rx_data_length[10]} {u1/u1/iprecieve_inst/rx_data_length[11]} {u1/u1/iprecieve_inst/rx_data_length[12]} {u1/u1/iprecieve_inst/rx_data_length[13]} {u1/u1/iprecieve_inst/rx_data_length[14]} {u1/u1/iprecieve_inst/rx_data_length[15]}]]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_CLK]
